name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build . --file Dockerfile --tag ghcr.io/nautes-labs/demo-bot:0.0.1-$IMAGE_TAG
        docker push ghcr.io/nautes-labs/demo-bot:0.0.1-$IMAGE_TAG
